language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coverage
script:
  - nosetests tests --with-coverage --cover-tests --cover-package=wrfda_urb/
after_success:
  - bash <(curl -s https://codecov.io/bash)
